# Generated by Django 6.0.5 on 2026-05-25 04:29

from django.db import migrations


def seed_migrations(apps, schema_editor):
    Membership = apps.get_model("users", "Membership")
    Membership.objects.update_or_create(
        code="basic",
        defaults={"price": 9900},
    )
    Membership.objects.update_or_create(
        code="premium",
        defaults={"price": 14900},
    )


def unseed_migrations(apps, schema_editor):
    Membership = apps.get_model("users", "Membership")
    Membership.objects.filter(code__in=["basic", "premium"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_migrations, unseed_migrations),
    ]
