# Generated by Django 6.0.5 on 2026-05-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_nickname_user_is_adult_mode_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created',
            new_name='created_at',
        ),
    ]
