# Generated by Django 6.0.5 on 2026-05-25 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_membership_subscription_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pending_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscriptions', to='users.membership'),
        ),
    ]
