# Generated by Django 6.0.5 on 2026-05-22 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        ('streams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watchinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchinghistory',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching_history', to='contents.video'),
        ),
        migrations.AlterUniqueTogether(
            name='watchinghistory',
            unique_together={('user', 'video')},
        ),
    ]
