# Generated by Django 6.0.5 on 2026-05-27 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('format_type', models.CharField(choices=[('1_COUR', '1쿨 (약 3개월/12화)'), ('2_COUR', '연속 2쿨 (약 6개월/24화)'), ('LONG', '장기 방영작 (원피스 등)'), ('MOVIE', '영화/극장판')], default='1_COUR', max_length=20)),
                ('start_date', models.DateField(help_text='방영/개봉 시작일')),
                ('end_date', models.DateField(blank=True, help_text='종료일 (미정이면 비워둠)', null=True)),
                ('genres', models.ManyToManyField(related_name='seasons', to='media.genre')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons', to='media.series')),
                ('tags', models.ManyToManyField(related_name='seasons', to='media.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('thumbnail_url', models.URLField()),
                ('episode_number', models.PositiveSmallIntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='media.season')),
            ],
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('series', 'name'), name='unique_season_per_series'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('season', 'episode_number')},
        ),
    ]
