# Generated by Django 6.0.5 on 2026-05-27 23:59

import django.db.models.deletion
import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_file', models.FileField(blank=True, null=True, upload_to=media.models.video_source_upload_to)),
                ('processing_status', models.CharField(choices=[('pending', '대기'), ('processing', '처리 중'), ('ready', '준비 완료'), ('failed', '실패')], default='pending', max_length=32)),
                ('storage_prefix', models.CharField(blank=True, max_length=512, null=True)),
                ('processing_error', models.CharField(blank=True, max_length=512, null=True)),
                ('manifest_url', models.URLField(blank=True, max_length=512, null=True)),
                ('thumbnail_url', models.URLField()),
                ('duration_seconds', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TranscodeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기'), ('processing', '처리 중'), ('succeeded', '성공'), ('failed', '실패')], default='pending', max_length=20)),
                ('backend', models.CharField(default='local_ffmpeg', max_length=32)),
                ('external_jbo_id', models.CharField(blank=True, max_length=128, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcode_jobs', to='media.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('format_type', models.CharField(choices=[('1_COUR', '1쿨 (약 3개월/12화)'), ('2_COUR', '연속 2쿨 (약 6개월/24화)'), ('LONG', '장기 방영작 (원피스 등)'), ('MOVIE', '영화/극장판')], default='1_COUR', max_length=20)),
                ('start_date', models.DateField(help_text='방영/개봉 시작일')),
                ('end_date', models.DateField(blank=True, help_text='종료일 (미정이면 비워둠)', null=True)),
                ('genres', models.ManyToManyField(related_name='seasons', to='media.genre')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons', to='media.series')),
                ('tags', models.ManyToManyField(related_name='seasons', to='media.tag')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('series', 'name'), name='unique_season_per_series')],
            },
        ),
    ]
